import { completionMessages } from '../src/chat/knowledge.js';
import { CHAT_CONFIG } from '../src/chat/config.js';
import type { ChatMessage } from '../src/chat/protocol.js';

// Vercel Node.js function. The key is never imported by the page.
declare const process: { env: Record<string, string | undefined> };
export const maxDuration = 60;
const headers = { 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff' };
const jsonError = (status: number, error: string, extra: Record<string, string> = {}) =>
  Response.json({ error }, { status, headers: { ...headers, ...extra } });

export function createChatHandler(options: { apiKey?: string; model?: string; fetchImpl?: typeof fetch } = {}) {
  // Per-instance abuse protection only; distributed limits belong in Vercel WAF.
  const buckets = new Map<string, { count: number; expires: number }>();
  return async (request: Request): Promise<Response> => {
    if (request.method !== 'POST') return jsonError(405, 'Please send a chat message using POST.', { Allow: 'POST' });
    const origin = request.headers.get('origin');
    if (origin !== new URL(request.url).origin || request.headers.get('sec-fetch-site') === 'cross-site') {
      return jsonError(403, 'Please use the assistant on our website.');
    }
    if (!request.headers.get('content-type')?.startsWith('application/json')) return jsonError(415, 'Chat messages must be JSON.');
    const key = options.apiKey;
    if (!key) return jsonError(503, 'The AI assistant is not configured yet. Please contact our team on WhatsApp.');
    const ip = request.headers.get('x-vercel-forwarded-for')?.split(',')[0].trim() || 'unknown';
    const now = Date.now();
    for (const [address, value] of buckets) if (value.expires <= now) buckets.delete(address);
    const bucket = buckets.get(ip) || { count: 0, expires: now + 60_000 };
    if (++bucket.count > 10 || (buckets.size >= 2000 && !buckets.has(ip))) return jsonError(429, 'Too many messages. Please wait a minute and try again.', { 'Retry-After': '60' });
    buckets.set(ip, bucket);
    let body: { question?: unknown; history?: unknown };
    try {
      // Bound streamed body before JSON parsing, not just Content-Length.
      const reader = request.body?.getReader();
      if (!reader) return jsonError(400, 'Please enter a question.');
      let bytes = 0, raw = ''; const decoder = new TextDecoder();
      while (true) {
        const { done, value } = await reader.read(); if (done) break;
        bytes += value.byteLength;
        if (bytes > 16_000) { await reader.cancel(); return jsonError(413, 'Your conversation is too long. Please start a New Chat.'); }
        raw += decoder.decode(value, { stream: true });
      }
      body = JSON.parse(raw + decoder.decode());
    } catch { return jsonError(400, 'The chat request could not be read. Please try again.'); }
    if (!body || typeof body !== 'object' || typeof body.question !== 'string' || !body.question.trim() || body.question.length > CHAT_CONFIG.maxInputCharacters) return jsonError(400, 'Please enter a question of 800 characters or fewer.');
    if (!Array.isArray(body.history) || body.history.length > 12) return jsonError(400, 'Invalid conversation history. Please start a New Chat.');
    const history: ChatMessage[] = [];
    for (const [index, item] of body.history.entries()) {
      if (!item || typeof item !== 'object' || item.role !== (index % 2 === 0 ? 'user' : 'assistant') || typeof item.content !== 'string' || !item.content.trim() || item.content.length > 3000) return jsonError(400, 'Invalid conversation history. Please start a New Chat.');
      history.push({ id: String(index), role: item.role, content: item.content });
    }
    if (history.length % 2 !== 0) return jsonError(400, 'Invalid conversation history. Please start a New Chat.');
    // Build authoritative system prompt/facts here. Never accept a client prompt,
    // model name, token limit, or key. All replies are generated by Groq.
    const messages = completionMessages(history, body.question.trim());
    const controller = new AbortController();
    const cancel = () => controller.abort();
    request.signal.addEventListener('abort', cancel, { once: true });
    const timeout = setTimeout(cancel, 50_000);
    const cleanup = () => { clearTimeout(timeout); request.signal.removeEventListener('abort', cancel); };
    const model = options.model || 'qwen/qwen3.8-27b';
    let upstream: Response;
    try {
      upstream = await (options.fetchImpl || fetch)('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST', signal: controller.signal,
        headers: { Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ model, ...(model === 'qwen/qwen3.8-27b' ? { reasoning_effort: 'none' } : {}), messages, stream: true, max_completion_tokens: 256, temperature: 0.3 }),
      });
    } catch { cleanup(); return jsonError(504, 'The AI connection timed out. Please try again.'); }
    if (!upstream.ok || !upstream.body) {
      cleanup(); void upstream.body?.cancel();
      if (upstream.status === 429) return jsonError(429, 'Our free AI allowance is temporarily exhausted. Please try later or contact our team on WhatsApp.', { 'Retry-After': '60' });
      return jsonError(503, 'The AI service is temporarily unavailable. Please try again or contact our team.');
    }
    const reader = upstream.body.getReader();
    const encoder = new TextEncoder();
    const stream = new ReadableStream<Uint8Array>({
      async start(output) {
        const emit = (data: object) => output.enqueue(encoder.encode(JSON.stringify(data) + '\n'));
        let pending = ''; const decoder = new TextDecoder(); let completed = false;
        try {
          while (!completed) {
            const { done, value } = await reader.read();
            if (done) throw new Error('Truncated AI stream');
            pending += decoder.decode(value, { stream: true }).replace(/\r/g, '');
            let boundary;
            while ((boundary = pending.indexOf('\n\n')) >= 0) {
              const event = pending.slice(0, boundary); pending = pending.slice(boundary + 2);
              const data = event.split('\n').filter(line => line.startsWith('data:')).map(line => line.slice(5).trim()).join('\n');
              if (!data) continue;
              if (data === '[DONE]') { completed = true; emit({ done: true }); break; }
              const chunk = JSON.parse(data);
              if (chunk.error) throw new Error('Provider stream error');
              const text = chunk.choices?.[0]?.delta?.content;
              if (typeof text === 'string' && text) emit({ text });
            }
          }
        } catch {
          if (!request.signal.aborted) { try { emit({ error: 'The AI response was interrupted. Please try again.' }); } catch { /* Browser closed. */ } }
        } finally {
          cleanup(); controller.abort(); await reader.cancel().catch(() => {});
          try { output.close(); } catch { /* Browser closed. */ }
        }
      },
      cancel() { cleanup(); controller.abort(); return reader.cancel().catch(() => {}); },
    });
    return new Response(stream, { headers: { ...headers, 'Content-Type': 'application/x-ndjson; charset=utf-8' } });
  };
}

// Conventional Vercel Node handler, compatible with the deployed Vite runtime.
interface NodeRequest extends AsyncIterable<Uint8Array> {
  method?: string;
  url?: string;
  headers: Record<string, string | string[] | undefined>;
  body?: unknown;
}
interface NodeResponse {
  statusCode: number;
  headersSent?: boolean;
  destroyed?: boolean;
  setHeader(name: string, value: string): void;
  write(chunk: Uint8Array): boolean;
  end(body?: string): void;
  on(event: string, callback: () => void): void;
  off(event: string, callback: () => void): void;
  once(event: string, callback: () => void): void;
}
export function createNodeHandler(options: Parameters<typeof createChatHandler>[0] = {}) {
  const handle = createChatHandler(options);
  return async (req: NodeRequest, res: NodeResponse) => {
    const controller = new AbortController();
    const abort = () => controller.abort();
    res.on('close', abort);
    try {
      const requestHeaders = new Headers();
      for (const [key, value] of Object.entries(req.headers)) if (value !== undefined) requestHeaders.set(key, Array.isArray(value) ? value.join(', ') : value);
      const protocol = requestHeaders.get('x-forwarded-proto')?.split(',')[0] || 'https';
      const host = requestHeaders.get('host');
      if (!host || !['http', 'https'].includes(protocol)) { res.statusCode = 400; res.end('Invalid request host'); return; }
      let raw = '';
      if (req.method === 'POST') {
        if (req.body !== undefined) raw = typeof req.body === 'string' ? req.body : JSON.stringify(req.body);
        else {
          const decoder = new TextDecoder(); let size = 0;
          for await (const chunk of req) {
            size += chunk.byteLength;
            if (size > 16000) { res.statusCode = 413; res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify({ error: 'Your conversation is too long. Please start a New Chat.' })); return; }
            raw += decoder.decode(chunk, { stream: true });
          }
          raw += decoder.decode();
        }
      }
      const request = new Request(new URL(req.url || '/api/chat', `${protocol}://${host}`), {
        method: req.method || 'GET', headers: requestHeaders, signal: controller.signal,
        ...(req.method === 'POST' ? { body: raw } : {}),
      });
      const response = await handle(request);
      res.statusCode = response.status;
      response.headers.forEach((value, key) => res.setHeader(key, value));
      if (response.body) {
        const reader = response.body.getReader();
        try {
          while (!res.destroyed) {
            const { done, value } = await reader.read(); if (done) break;
            if (!res.write(value)) await new Promise<void>(resolve => {
              const finish = () => { res.off('drain', finish); res.off('close', finish); resolve(); };
              res.once('drain', finish); res.once('close', finish);
            });
          }
        } finally { await reader.cancel().catch(() => {}); }
      }
      res.end();
    } catch {
      // No prompts, credentials, or provider responses are logged.
      if (!res.headersSent) { res.statusCode = 500; res.setHeader('Content-Type', 'application/json'); }
      if (!res.destroyed) res.end(JSON.stringify({ error: 'The AI assistant encountered a server error. Please try again.' }));
    } finally { res.off('close', abort); controller.abort(); }
  };
}
let nodeHandler: ReturnType<typeof createNodeHandler> | undefined;
export default async function chat(req: NodeRequest, res: NodeResponse) {
  nodeHandler ||= createNodeHandler({ apiKey: process.env.GROQ_API_KEY, model: process.env.GROQ_MODEL });
  return nodeHandler(req, res);
}
